Modelization: Modelization::Registration Class Reference
Modelization::Registration Class Reference
Registration Class.
#include <Registration.hpp>
Public Member Functions
Registration (bool _rejection=true, bool _reciprocal=true, float VfiltSize=0.01, int _Threshold=1000)
Registration Main constructor.
virtual ~Registration ()
Default empty destructor.
bool addCloud (const PCXYZRGBCPtr &_in)
Main Loop registration function Multithreaded.
bool getResult (PCXYZRGBPtr &_out)
Get View Multithreaded.
void runLoop (const PCXYZRGBPtr &_in)
Main Loop registration function.
void run (const PCXYZRGBPtr &_src, const PCXYZRGBPtr &_tgt, PCXYZRGB &cloud_r)
Registration test function not looped.
void getView (PCXYZRGBPtr &result, bool doTransform, bool forceUpdate)
returns the registration result from images given by the runLoop function
Detailed Description
Registration Class.
Definition at line 54 of file Registration.hpp.
Constructor & Destructor Documentation
Modelization::Registration::Registration (bool _rejection = true, bool _reciprocal = true, float VfiltSize = 0.01, int _Threshold = 1000)
Registration Main constructor.
Parameters
[in] _rejection Enable the bad correspondance rejections for the transformation estimation
[in] _reciprocal if true all correspondances must
[in] VfiltSize Voxel filter size in meters
[in] _Threshold Minimum number of correspondences to determine a valid keyframe be reciprocal in order to be considered as a valid correspondance
Definition at line 14 of file Registration.cpp.
Member Function Documentation
bool Modelization::Registration::addCloud (const PCXYZRGBCPtr & _in)
Main Loop registration function Multithreaded.
Warning
the image must not be changed.
Parameters
[in] _in the input cloud to be added to the registration
Definition at line 37 of file Registration.cpp.
References runLoop().
Referenced by Modelization::LiveRegistrator::run().
bool Modelization::Registration::getResult (PCXYZRGBPtr & _out)
Get View Multithreaded.
Parameters
[out] _out the resultant cloud
Definition at line 51 of file Registration.cpp.
References getView().
Referenced by Modelization::LiveRegistrator::run().
void Modelization::Registration::getView (PCXYZRGBPtr & result, bool doTransform, bool forceUpdate)
returns the registration result from images given by the runLoop function
Parameters
[out] result the complete registered cloud.
[in] doTransform Apply the transformation matrix.
[in] forceUpdate rebuild the result cloud from scratch
Definition at line 534 of file Registration.cpp.
References Modelization::planeDetection::voxel_filter().
Referenced by getResult().
void Modelization::Registration::run (const PCXYZRGBPtr & _src, const PCXYZRGBPtr & _tgt, PCXYZRGB & cloud_r)
Registration test function not looped.
Parameters
[in] _src source cloud.
[in] _tgt target cloud.
[out] cloud_r Resulting cloud from registration.
Definition at line 131 of file Registration.cpp.
void Modelization::Registration::runLoop (const PCXYZRGBPtr & _in)
Main Loop registration function.
Parameters
[in] _in the input cloud to be added to the registration
Definition at line 77 of file Registration.cpp.
Referenced by addCloud().
The documentation for this class was generated from the following files:
include/Registration.hpp
src/Registration.cpp